config/routes.rb
Rails.application.routes.draw do
  get 'customers/search'
  get 'vehicles/search'
  get 'pages/help'
  get 'reports/employee_hour_weekly'
  get 'reports/employee_hour_monthly'
  get 'reports/service_revenue_weekly'
  get 'reports/service_revenue_monthly'

  resources :reports
  resources :transmissions
  resources :models
  resources :makes
  resources :ticketstatuses
  resources :servicepositions
  resources :serviceactions
  resources :servicelines
  resources :employees
  resources :services
  resources :categories
  resources :tickets do
    resources :servicelines
  end
  resources :vehicles do
    resources :tickets
  end
  resources :customers do
    resources :vehicles do
      resources :tickets
    end
  end
  get 'tickets/index'
  get 'tickets/update_services', as: 'update_services'
  get 'tickets/show'

  root 'pages#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :vehicles, :dependent => :destroy

  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :phone
  validates :state, length: {maximum:2}, :allow_blank => true
  validates :zip, length: {maximum:10}, :allow_blank => true
  validates :phone, length: { minimum: 10, maximum: 12 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, }, :allow_blank => true

  def full_name
    "#{last_name}, #{first_name}"
  end

  def self.simplesearch(simplesearch)
    if simplesearch
      where('last_name LIKE ? OR first_name LIKE ? OR phone LIKE ?', "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%")
    else
      scoped
    end
  end

  def self.search(search, condition)
    if condition
      self.where("#{condition[0]} LIKE ?", '%'+search+'%')
    else
      []
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
    respond_to do |format|
      format.html  #index.html.erb
      format.json { render json: @customers }

    if params[:simplesearch]
      @customers = Customer.simplesearch(params[:simplesearch]).order("last_name ASC, first_name ASC").paginate(page: params[:page], per_page: 15)
      if @customers.blank?
        flash.now[:alert] = "Your search does not match any record. Please try again or Create A New Customer."
      end
    else
      @customers = Customer.all.order("created_at DESC").paginate(page: params[:page], per_page: 15)
    end
    end
  end

  def search
    @customers = Customer.search(params[:search], params[:condition])
    if @customers.blank?
      flash.now[:alert] = "Your search does not match any record. Please try again or Create A New Ticket."
    end
  end
  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:last_name, :first_name, :address, :city, :state, :zip, :phone, :email, :additional_contact)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-dismissible alert-danger"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</div>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li class="alert alert-dismissible alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
   <% end %>

  <fieldset style="background-color: #E7F5FF; opacity: 1; border: 1px solid #c0c0c0;
          margin: 0 5px; padding: 1em 1em 1em; max-width: 900px">
  <div class="form-group">
    <%= f.label :last_name, 'Name*:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :first_name, :class => 'form-control', :placeholder => 'First Name (Required)' %>
    <%= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last Name (Required)' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, "Address:", :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :address, :class => 'form-control', :placeholder => 'Home Address' %>
    <%= f.text_field :city, :class => 'form-control col-sm-3', :placeholder => 'City' %>
    <%= f.text_field :state, :class => 'form-control col-sm-2', :placeholder => 'State (e.g. TX)' %>
    <%= f.number_field :zip, :class => 'form-control col-sm-2', :placeholder => 'ZIP' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :phone, 'Phone*:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :phone, :class => 'form-control', :placeholder => '5555555555 (Required)' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, 'E-mail:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :email, :class => 'form-control', :placeholder => 'john.doe@gmail.com' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :additional_contact, 'Additional Contact:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :additional_contact, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit 'Add Customer', :class => 'btn btn-info btn-sm' %>
    <%= link_to 'Cancel', customers_path, :class => 'btn btn-default btn-sm' %>
    </div>
  </div>
    </fieldset>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>
<br>
<%= link_to 'View Customer', @customer, :class => 'btn btn-success btn-xs' %>
<%= link_to 'View All Customers', customers_path, :class => 'btn btn-default btn-xs' %>

app/views/customers/index.html.erb
<%= form_tag customers_path, :html => { :class => "form-horizontal"}, :method => 'get', :id => "simplesearch" do %>
    <fieldset style="background-color: #f4f4f4; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
      <legend>Search Customer</legend>
      <%= text_field_tag :simplesearch, params[:simplesearch], placeholder: "Enter Name or Phone Number to Search",
                         :id => 'search_field', :class => 'col-xs-6' %>
      <%= submit_tag "Search", :customer_vehicle => nil, :customer_vehicle =>  nil, :total => nil, :class => 'btn btn-default  btn-xs' %>
      <%= link_to 'Clear', customers_path, :class => 'btn btn-success btn-xs' %>
      <%= link_to 'Advanced Search', customers_search_path, :class => "btn btn-info btn-xs" %>
    </fieldset>
<% end %>
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<% if alert %><p class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button><%= alert %></p><% end %>

<h1>Customer</h1>
<%= link_to 'Add New Customer', new_customer_path, :class => 'btn btn-info btn-sm' %>
<br><br>
<table id="myTable" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>ZIP</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Additional Contact</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer), :class => "btn btn-link btn-xs" %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.first_name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.zip %></td>
        <td><%= number_to_phone(customer.phone, area_code: true) %></td>
        <td><%= customer.email %></td>
        <td><%= customer.additional_contact %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), :class => "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => "btn btn-danger btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center><p class="pagination-sm">
  <%= will_paginate @customers , renderer: BootstrapPagination::Rails %>
</p></center>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

app/views/customers/search.html.erb
<p id="notice"><%= notice %></p>
<fieldset style="background-color: #f4f4f4; opacity: 1; border: 1px solid #c0c0c0;
        margin: 0 5px; padding: 1em 2em 1em;">
<div id="search" class="form-group">
  <%= form_tag customers_search_path, :remote => true, :method => 'get', :class => 'form-inline' do %>
      <%= text_field_tag :search, params[:search], :id => 'search_field', :class => 'form-control' %>
      <%= collection_select :condition, params[:to_s], Customer.column_names, :to_s, :titleize, {}, :class => 'form-control' %>
      <%= submit_tag "Search", :name => nil, :class => 'btn btn-info btn-sm' %>
  <% end %>
  <h2>Results</h2>
  <table id="results" class="table table-striped table-condensed table-hover">
    <thead>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Phone</th>
        <th>Email</th>
    </thead>
    <tbody>
    <% @customers.each do |customer| %>
        <tr class="info">
          <td><%= link_to customer.full_name, :action => 'show', :id => customer.id  %></td>
          <td><%= customer.address %></td>
          <td><%= customer.city %></td>
          <td><%= customer.state %></td>
          <td><%= customer.zip %></td>
          <td><%= customer.phone %></td>
          <td><%= customer.email %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

       <script>
      $("#search > form").submit(customer_results)
      $("#search_field").bind("keyup mouseup mousewheel", customer_results)
      $("#function_").on("change", function(){customer_results()})
      function customer_results() {
          var url = $("#search > form").attr("action") + "?" + $("#search > form").serialize();
          var results_page = " #results"
          if ($("#search_field").val().length > 0) {
              $("#results").load(url + results_page)
          }
      }
  </script>
</div>
</fieldset>

app/views/customers/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<p>
<h2><%= @customer.full_name %></h2>
</p>
<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @customer.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @customer.zip %>
</p>

<p>
  <strong>Phone:</strong>
  <%= number_to_phone(@customer.phone, area_code: true) %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>

<p>
  <strong>Additional contact:</strong>
  <%= @customer.additional_contact %>
</p>
<center><p class="lead">Vehicles Owned</p></center>
<table class="table table-striped table-hover table-condensed">
  <thead>
  <tr>
    <th>ID</th>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>License</th>
    <th>Mile</th>
    <th>Engine</th>
    <th>Transmission</th>
    <th>VIN</th>
    <th>Action</th>
  </tr>
  </thead>
  <% @customer.vehicles.each do |car| %>
      <tr class="info">
        <td><%= link_to car.id, vehicle_path(car) %></td>
        <td><%= car.year %></td>
        <td><%= if car.make; car.make.make end %></td>
        <td><%= if car.model; car.model.model end %></td>
        <td><%= car.license %></td>
        <td><%= car.mile %></td>
        <td><%= car.engine %></td>
        <td><%= if car.transmission; car.transmission.transmission end %></td>
        <td><%= car.vin %></td>
        <td><%= link_to 'Edit Vehicle', edit_vehicle_path(car), :class => 'btn btn-info btn-xs' %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Add New Vehicle', new_vehicle_path, :class => 'btn btn-info btn-sm' %>
<%= link_to 'Edit', edit_customer_path(@customer), :class => 'btn btn-primary btn-sm' %>
<%= link_to 'View All Customers', customers_path, :class => 'btn btn-default btn-sm' %>