config/routes.rb
Rails.application.routes.draw do
  get 'customers/search'
  get 'vehicles/search'
  get 'pages/help'
  get 'reports/employee_hour_weekly'
  get 'reports/employee_hour_monthly'
  get 'reports/service_revenue_weekly'
  get 'reports/service_revenue_monthly'

  resources :reports
  resources :transmissions
  resources :models
  resources :makes
  resources :ticketstatuses
  resources :servicepositions
  resources :serviceactions
  resources :servicelines
  resources :employees
  resources :services
  resources :categories
  resources :tickets do
    resources :servicelines
  end
  resources :vehicles do
    resources :tickets
  end
  resources :customers do
    resources :vehicles do
      resources :tickets
    end
  end
  get 'tickets/index'
  get 'tickets/update_services', as: 'update_services'
  get 'tickets/show'

  root 'pages#home'

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :transmission
  has_many :tickets, :dependent => :destroy
  validates_presence_of :customer
  validates_presence_of :make
  validates_presence_of :model
  validates_presence_of :transmission
  validates_presence_of :license
  validates_presence_of :vin
  validates :vin, length: {maximum:17}
  before_save :uppercase

  def uppercase
    self.license.upcase!
    self.vin.upcase!
  end
  def customer_vehicle
    "#{customer.full_name} - #{year}, #{make.make}, #{model.model}, #{license}"
  end
  def vehicle_info
    "#{year}, #{make.make} - #{model.model}, #{license}"
  end
  def yearmakemodel
    "#{year}, #{make.make} - #{model.model}"
  end

  def self.simplesearch(simplesearch)
    if simplesearch
      return includes(:make, :model, :customer).
          where("make LIKE ? OR model LIKE ? OR first_name LIKE ? or last_name LIKE ?", "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%").
          references(:make, :model, :customer)
    else
      scoped
    end
  end

  def self.search(search, condition)
    if condition
      self.where("#{condition[0]} LIKE ?", '%'+search+'%')
    else
      []
    end
  end
  # def self.search(search, condition)
  #   if condition
  #     return includes(:make, :model, :customer).
  #     where("#{condition[0]} LIKE ? OR make LIKE ? OR model LIKE ? OR first_name LIKE ? OR last_name LIKE ?",'%'+search+'%', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").
  #     references(:make, :model, :customer)
  #   else
  #     []
  #   end
  # end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
    respond_to do |format|
      format.html  #index.html.erb
      format.json { render json: @vehicles }
    @makes = Make.all
    @models = Model.where("make_id = ?", Make.first.id)
    if params[:simplesearch]
      @vehicles = Vehicle.simplesearch(params[:simplesearch]).order("last_name ASC, first_name ASC").paginate(:page => params[:page], :per_page => 30)
      if @vehicles.blank?
        flash.now[:alert] = "Your search does not match any record. Please try again or Create A New Vehicle."
      end
    else
      @vehicles = Vehicle.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 30)
    end
    end
  end

  def search
    @vehicles = Vehicle.search(params[:search], params[:condition])
    if @vehicles.blank?
      flash.now[:alert] = "Your search does not match any record. Please try again or Create A New Ticket."
    end
  end
  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  def update_models
    @models = Model.where("make_id = ?", params[:make_id])
    respond_to do |format|
      format.js
    end
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:year, :make, :model, :gvw, :license, :mile, :engine, :vin, :customer_id,
      :make_id, :model_id, :transmission_id)
    end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for @vehicle, :html => { :class => 'form-horizontal' }  do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-dismissible alert-danger"><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</div>
      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li class="alert alert-dismissible alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="background-color: #E7F5FF; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 5px; padding: 1em 2em 1em; max-width: 900px">
    <div class="form-group">
      <%= f.label :customer_id, 'Customer:', :class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
        <%= f.collection_select :customer_id, Customer.order("created_at DESC"), :id, :full_name, {},
                              class: "form-control" %>
      </div>
    </div>
  <div class="form-group">
    <%= f.label :year, 'Year:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.select(:year, 1960..2050, {:selected=>(f.object.year||Date.today.year)},:class => 'form-control') %>
    </div>
  </div>
  <div class="form-group">
  <%= f.label :make_id, 'Make:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.collection_select :make_id, Make.all, :id, :make, {}, :class => 'form-control' %>
    </div>
</div>
  <div class="form-group">
    <%= f.label :model_id, 'Model:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.grouped_collection_select :model_id, Make.order(:make), :models, :make, :id, :model, {},
                                    :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :license, 'License Plate*:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :license, :class => 'form-control', :placeholder => 'ABC1234 (Required)' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mile, 'Mileage:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :mile, :class => 'form-control', :placeholder => '25000' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :engine, 'Engine:',:class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :engine, :class => 'form-control', :placeholder => 'V6' %>
    </div>
  </div>
    <div class="form-group">
      <%= f.label :transmission_id, 'Transmission:',:class => 'col-sm-2 control-label' %>
      <div class="col-sm-10">
      <%= f.collection_select :transmission_id, Transmission.all, :id, :transmission,{},
                              :class => 'form-control' %>
      </div>
    </div>
  <div class="form-group">
    <%= f.label :vin, 'VIN*:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :vin, :class => 'form-control', :placeholder => 'Vehicle Identification Number (Required)' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit 'Add Vehicle', :class => 'btn btn-info btn-sm' %>
    <%= link_to 'Cancel', vehicles_path, :class => 'btn btn-default btn-sm' %>
  </div>
      </div>
    </fieldset>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form' %>
<br>
<%= link_to 'View Vehicle', @vehicle, :class => 'btn btn-success btn-xs' %>
<%= link_to 'View All Vehicles', vehicles_path, :class => 'btn btn-default btn-xs' %>

app/views/vehicles/index.html.erb
<%= form_tag vehicles_path, :class => "form-horizontal", :method => 'get', :id => "simplesearch" do %>
    <fieldset style="background-color: #f4f4f4; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 2px; padding: 0.35em 0.625em 0.75em;" >
      <legend>Search Vehicle</legend>
      <%= text_field_tag :simplesearch, params[:simplesearch], placeholder: "Enter Customer Name or Car Make/Model to search",
                         :id => 'search_field', :class => 'col-xs-6' %>
      <%= submit_tag "Search", :class => 'btn btn-default btn-xs' %>
      <%= link_to 'Clear', vehicles_path, :class => 'btn btn-success btn-xs' %>
      <%= link_to 'Advanced Search', vehicles_search_path, :class => "btn btn-info btn-xs" %>
    </fieldset>
<% end %>

<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<% if alert %><p class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button><%= alert %></p><% end %>

<h1>Vehicles</h1>
<%= link_to 'Add New Vehicle', new_vehicle_path, :class => 'btn btn-info btn-sm' %>
<br><br>
<table id="myTable" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Customer</th>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>License</th>
      <th>Mile</th>
      <th>Engine</th>
      <th>Transmission</th>
      <th>Vin</th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= link_to vehicle.id, vehicle_path(vehicle), :class => "btn btn-link btn-xs" %></td>
        <td><%= if vehicle.customer; vehicle.customer.full_name end%></td>
        <td><%= vehicle.year %></td>
        <td><%= if vehicle.make; vehicle.make.make end %></td>
        <td><%= if vehicle.model; vehicle.model.model end %></td>
        <td><%= vehicle.license %></td>
        <td><%= number_with_precision(vehicle.mile, :precision => 0, :delimiter => ',') %></td>
        <td><%= vehicle.engine %></td>
        <td><%= if vehicle.transmission; vehicle.transmission.transmission end %></td>
        <td><%= vehicle.vin %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle), :class => "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Delete', vehicle, method: :delete, data: { confirm: 'Are you sure?' },
                        :class => "btn btn-danger btn-xs"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<center><p class="pagination-sm">
  <%= will_paginate @customers , renderer: BootstrapPagination::Rails %>
</p></center>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form' %>

app/views/vehicles/search.html.erb
<p id="notice"><%= notice %></p>
<fieldset style="background-color: #f4f4f4; opacity: 1; border: 1px solid #c0c0c0;
        margin: 0 5px; padding: 1em 2em 1em;">
  <div id="search" class="form-group">
    <%= form_tag vehicles_search_path, :remote => true, :method => 'get', :class => 'form-inline' do %>
        <%= text_field_tag :search, params[:search], :id => 'search_field', :class => 'form-control' %>
        <select id="condition_" name="condition[]" class="form-control">
          <option value="id">Vehicle ID</option>
          <option value="customer_id">Customer ID</option>
          <option value="year">Year</option>
          <option value="make_id">Make ID</option>
          <option value="model_id">Model ID</option>
          <option value="license">License Plate</option>
          <option value="mile">Mile</option>
          <option value="engine">Engine</option>
          <option value="transmission_id">Transmission ID</option>
          <option value="vin">VIN</option>
          <option value="created_at">Created At</option>
          <option value="updated_at">Updated At</option>
        </select>
        <%= submit_tag "Search", :name => nil, :class => 'btn btn-info btn-sm' %>
    <% end %>
    <h2>Results</h2>
    <table id="results" class="table table-striped table-condensed table-hover">
      <thead>
      <th>Vehicle</th>
      </thead>
      <tbody>
      <% @vehicles.each do |vehicle| %>
          <tr class="info">
            <td><%= link_to vehicle.customer_vehicle, :action => 'show', :id => vehicle.id  %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <script>
        $("#search > form").submit(vehicle_results)
        $("#search_field").bind("keyup mouseup mousewheel", vehicle_results)
        $("#function_").on("change", function(){vehicle_results()})
        function vehicle_results() {
            var url = $("#search > form").attr("action") + "?" + $("#search > form").serialize();
            var results_page = " #results"
            if ($("#search_field").val().length > 0) {
                $("#results").load(url + results_page)
            }
        }
    </script>

  </div>
</fieldset>

app/views/vehicles/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<p>
  <h2><%= if @vehicle.customer; @vehicle.customer.full_name end %></h2>
</p>
<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= if @vehicle.make; @vehicle.make.make end %>
</p>

<p>
  <strong>Model:</strong>
  <%= if @vehicle.model; @vehicle.model.model end %>
</p>

<p>
  <strong>License:</strong>
  <%= @vehicle.license %>
</p>

<p>
  <strong>Mile:</strong>
  <%= number_with_precision(@vehicle.mile, :precision => 0, :delimiter => ',') %>
</p>

<p>
  <strong>Engine:</strong>
  <%= @vehicle.engine %>
</p>
<p>
  <strong>Transmission:</strong>
  <%= if @vehicle.transmission; @vehicle.transmission.transmission end %>
</p>

<p>
  <strong>VIN:</strong>
  <%= @vehicle.vin %>
</p>
<center><p class="lead">Tickets</p></center>
<table class="table table-striped table-hover table-condensed">
  <thead>
  <tr>
    <th>Ticket #</th>
    <th>Vehicle</th>
    <th>Note</th>
    <th>Status</th>
    <th>Total</th>
    <th>Action</th>
  </tr>
  </thead>
  <% @vehicle.tickets.each do |ticket| %>
      <tr class="info">
        <td><%= link_to ticket.id, ticket_path(ticket) %></td>
        <td><%= if ticket.vehicle; ticket.vehicle.vehicle_info end %></td>
        <td><%= ticket.note %></td>
        <td><%= if ticket.ticketstatus; ticket.ticketstatus.status end %></td>
        <td><%= number_to_currency(ticket.total) %></td>
        <td><%= link_to 'Edit Ticket', edit_ticket_path(ticket), :class => 'btn btn-info btn-xs' %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'Add New Ticket', new_ticket_path, :class => 'btn btn-info btn-sm' %>
<%= link_to 'Edit', edit_vehicle_path(@vehicle), :class => 'btn btn-primary btn-sm' %>
<%= link_to 'View All Vehicles', vehicles_path, :class => 'btn btn-default btn-sm' %>