config/routes.rb
Rails.application.routes.draw do
  get 'customers/search'
  get 'vehicles/search'
  get 'pages/help'
  get 'reports/employee_hour_weekly'
  get 'reports/employee_hour_monthly'
  get 'reports/service_revenue_weekly'
  get 'reports/service_revenue_monthly'

  resources :reports
  resources :transmissions
  resources :models
  resources :makes
  resources :ticketstatuses
  resources :servicepositions
  resources :serviceactions
  resources :servicelines
  resources :employees
  resources :services
  resources :categories
  resources :tickets do
    resources :servicelines
  end
  resources :vehicles do
    resources :tickets
  end
  resources :customers do
    resources :vehicles do
      resources :tickets
    end
  end
  get 'tickets/index'
  get 'tickets/update_services', as: 'update_services'
  get 'tickets/show'

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :services, :dependent => :destroy
  has_many :servicelines, :dependent => :destroy
  validates_presence_of :category_name
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :vehicles, :dependent => :destroy

  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :phone
  validates :state, length: {maximum:2}, :allow_blank => true
  validates :zip, length: {maximum:10}, :allow_blank => true
  validates :phone, length: { minimum: 10, maximum: 12 }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, }, :allow_blank => true

  def full_name
    "#{last_name}, #{first_name}"
  end

  def self.simplesearch(simplesearch)
    if simplesearch
      where('last_name LIKE ? OR first_name LIKE ? OR phone LIKE ?', "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%")
    else
      scoped
    end
  end

  def self.search(search, condition)
    if condition
      self.where("#{condition[0]} LIKE ?", '%'+search+'%')
    else
      []
    end
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :servicelines, :dependent => :destroy
  validates_presence_of :last_name
  validates_presence_of :first_name
  validates_presence_of :phone
  validates :phone, length: { minimum: 10, maximum: 12 }

  def full_name
    "#{last_name}, #{first_name}"
  end
end

app/models/make.rb
class Make < ActiveRecord::Base
  has_many :models, :dependent => :destroy
  has_many :vehicles, :dependent => :destroy
  validates_presence_of :make
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :make
  has_many :vehicles, :dependent => :destroy
  validates_presence_of :model
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :category
  has_many :servicelines, :dependent => :destroy
  validates_presence_of :service_name
end

app/models/serviceaction.rb
class Serviceaction < ActiveRecord::Base
  has_many :servicelines, :dependent => :destroy
  validates_presence_of :action
end

app/models/serviceline.rb
class Serviceline < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :category
  belongs_to :employee
  belongs_to :service
  belongs_to :serviceaction
  belongs_to :serviceposition
  after_save :calculate_total

  def calculate_total
    self.ticket.calculate_total!
  end
  #before_save :calculate_subtotal

  # def calculate_subtotal
  #   self.subtotal += ((self.hour * self.rate)+(self.quantity * self.part_price)).round(2)
  # end
end

app/models/serviceposition.rb
class Serviceposition < ActiveRecord::Base
  has_many :servicelines, :dependent => :destroy
  validates_presence_of :position
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :servicelines, :dependent => :destroy
  belongs_to :vehicle
  belongs_to :ticketstatus

  def self.simplesearch(simplesearch)
    if simplesearch
      return includes(:vehicle).
          where("make_id LIKE ? or model_id LIKE ?", "%#{simplesearch}%", "%#{simplesearch}%").
          references(:vehicle)
    else
      scoped
    end
  end
  def calculate_total!
    self.update_column(:total, self.servicelines.sum(:subtotal))
  end

  def ticket_info
    "##{vehicle.id} - #{vehicle.make.make}, #{vehicle.model.model} - #{vehicle.customer.full_name}"
  end
end

app/models/ticketstatus.rb
class Ticketstatus < ActiveRecord::Base
  has_many :tickets, :dependent => :destroy
  validates_presence_of :status
end

app/models/transmission.rb
class Transmission < ActiveRecord::Base
  has_many :vehicles, :dependent => :destroy
  validates_presence_of :transmission
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :transmission
  has_many :tickets, :dependent => :destroy
  validates_presence_of :customer
  validates_presence_of :make
  validates_presence_of :model
  validates_presence_of :transmission
  validates_presence_of :license
  validates_presence_of :vin
  validates :vin, length: {maximum:17}
  before_save :uppercase

  def uppercase
    self.license.upcase!
    self.vin.upcase!
  end
  def customer_vehicle
    "#{customer.full_name} - #{year}, #{make.make}, #{model.model}, #{license}"
  end
  def vehicle_info
    "#{year}, #{make.make} - #{model.model}, #{license}"
  end
  def yearmakemodel
    "#{year}, #{make.make} - #{model.model}"
  end

  def self.simplesearch(simplesearch)
    if simplesearch
      return includes(:make, :model, :customer).
          where("make LIKE ? OR model LIKE ? OR first_name LIKE ? or last_name LIKE ?", "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%", "%#{simplesearch}%").
          references(:make, :model, :customer)
    else
      scoped
    end
  end

  def self.search(search, condition)
    if condition
      self.where("#{condition[0]} LIKE ?", '%'+search+'%')
    else
      []
    end
  end
  # def self.search(search, condition)
  #   if condition
  #     return includes(:make, :model, :customer).
  #     where("#{condition[0]} LIKE ? OR make LIKE ? OR model LIKE ? OR first_name LIKE ? OR last_name LIKE ?",'%'+search+'%', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%").
  #     references(:make, :model, :customer)
  #   else
  #     []
  #   end
  # end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/makes_helper.rb
module MakesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => 'form-horizontal' }  do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-dismissible alert-danger"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</div>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li class="alert alert-dismissible alert-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <fieldset style="background-color: #E7F5FF; opacity: 1; border: 1px solid #c0c0c0;
            margin: 0 5px; padding: 1em 1em 1em; max-width: 900px">
  <div class="form-group">
    <%= f.label :category_name, 'Category*:', :class => 'col-sm-2 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :category_name, :class => 'form-control', :placeholder => 'Brake' %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
    <%= f.submit 'Add Category', :class => 'btn btn-info btn-sm' %>
      <%= link_to 'Cancel', categories_path, :class => 'btn btn-default btn-sm' %>
    </div>
  </div>
  </fieldset>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>
<br>
<%= link_to 'View Category', @category, :class => 'btn btn-success btn-xs' %>
<%= link_to 'View All Categories', categories_path, :class => 'btn btn-default btn-xs' %>

app/views/categories/index.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>
<% if alert %><p class="alert alert-dismissible alert-danger">
  <button type="button" class="close" data-dismiss="alert">×</button><%= alert %></p><% end %>

<h1>Category</h1>
<%= link_to 'Add New Category', new_category_path, :class => 'btn btn-info btn-sm' %>
<br><br>
<table id="myTable" class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>#</th>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category), :class => "btn btn-link btn-xs" %></td>
        <td><%= category.category_name %></td>
        <td><%= link_to 'Edit', edit_category_path(category), :class => "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<% if notice %><p class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">×</button><%= notice %></p><% end %>

<p>
  <strong>Category name:</strong>
  <%= @category.category_name %>
</p>
<%= link_to 'Add A Service To Category', new_service_path, :class => 'btn btn-info btn-sm' %>
<%= link_to 'Edit', edit_category_path(@category), :class => 'btn btn-primary btn-sm' %>
<%= link_to 'View All Categories', categories_path, :class => 'btn btn-default btn-sm' %>