config/routes.rb
Rails.application.routes.draw do
  get 'customers/search'
  get 'vehicles/search'
  get 'pages/help'
  get 'reports/employee_hour_weekly'
  get 'reports/employee_hour_monthly'
  get 'reports/service_revenue_weekly'
  get 'reports/service_revenue_monthly'

  resources :reports
  resources :transmissions
  resources :models
  resources :makes
  resources :ticketstatuses
  resources :servicepositions
  resources :serviceactions
  resources :servicelines
  resources :employees
  resources :services
  resources :categories
  resources :tickets do
    resources :servicelines
  end
  resources :vehicles do
    resources :tickets
  end
  resources :customers do
    resources :vehicles do
      resources :tickets
    end
  end
  get 'tickets/index'
  get 'tickets/update_services', as: 'update_services'
  get 'tickets/show'

  root 'pages#home'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def employee_hour_weekly
    @weeklyhours1 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Bates").id, created_at: [1.week.ago..Time.now])
    @weeklyhours2 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Fierro").id, created_at: [1.week.ago..Time.now])
    @weeklyhours3 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Koslosky").id, created_at: [1.week.ago..Time.now])
    respond_to do |format|
      format.html
      format.pdf
    end
  end
  def employee_hour_monthly
    @monthlyhours1 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Bates").id, created_at: [1.month.ago..Time.now])
    @monthlyhours2 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Fierro").id, created_at: [1.month.ago..Time.now])
    @monthlyhours3 = Serviceline.order("created_at DESC").
        where(:employee_id => Employee.find_by(last_name: "Koslosky").id, created_at: [1.month.ago..Time.now])
    respond_to do |format|
      format.html
      format.pdf
    end
  end
  def service_revenue_weekly
    @totalweek = Serviceline.where(created_at: [1.week.ago..Time.now])
    @weeklyrevenue1 = Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id,
                                        created_at: [1.week.ago..Time.now])
    @weeklyrevenue2 = Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id,
                                        created_at: [1.week.ago..Time.now])
    @weeklyrevenue3 = Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id,
                                        created_at: [1.week.ago..Time.now])
    respond_to do |format|
      format.html
      format.pdf
    end
  end
  def service_revenue_monthly
    @totalmonth = Serviceline.where(created_at: [1.month.ago..Time.now])
    @monthlyrevenue1 = Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id,
                                        created_at: [1.month.ago..Time.now])
    @monthlyrevenue2 = Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id,
                                        created_at: [1.month.ago..Time.now])
    @monthlyrevenue3 = Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id,
                                        created_at: [1.month.ago..Time.now])
    respond_to do |format|
      format.html
      format.pdf
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/employee_hour_monthly.html.erb
<div class="jumbotron">
  <center><h2 >Total Employee Hours In Last 1 Month </h2></center>
  <center><h3 class="lead">( From <%=1.month.ago.strftime("%D") %> to <%= Time.now.strftime("%D")%> )</h3></center>
  <p><%= link_to "Print PDF", reports_employee_hour_monthly_path(@report, :format => 'pdf'), :class => 'btn btn-success' %></p>
  <table id="myTable" class="table table-striped table-hover" style="max-width: 600px">
    <thead>
    <tr bgcolor="#FFFFFF">
      <th><font size="3px">Employee</font></th>
      <th><font size="3px">Total Hour(s)</font></th>
    </tr>
    </thead>
    <tbody>
    <tr class="info">
      <td>John Bates</td>
      <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Bates").id, created_at: [1.month.ago..Time.now]).sum(:hour) %></td>
    </tr>
    <tr class="info">
      <td>Matt Fierro</td>
      <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Fierro").id, created_at: [1.month.ago..Time.now]).sum(:hour) %></td>
    </tr>
    <tr class="info">
      <td>Billy Koslosky</td>
      <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Koslosky").id, created_at: [1.month.ago..Time.now]).sum(:hour) %></td>
    </tr>
    </tbody>
  </table>

  <select id="thechoices" class="form-control" style="max-width: 800px">
    <option>Select Employee to View More Details</option>
    <option value="johntab">John Bates</option>
    <option value="matttab">Matt Fierro</option>
    <option value="billtab">Bill Koslosky</option>
  </select>
  <br>

  <!--John's Hours-->
 <div id="johntab">
    <div class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">John Bates</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @monthlyhours1.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>

  <!--Matt's Hours-->
<div id="matttab">
    <div class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">Matt Fierro</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @monthlyhours2.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>


  <!--Bill's Hours-->
<div id="billtab">
    <div class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">Bill Koslosky</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @monthlyhours3.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#johntab').hide();
        $('#matttab').hide();
        $('#billtab').hide();
        $("#thechoices").change(function(){
            $('#johntab').hide();
            $('#matttab').hide();
            $('#billtab').hide();
            $("#" + this.value).show();
        });

        $("#thechoices").change();
    });
</script>

app/views/reports/employee_hour_weekly.html.erb
<div class="jumbotron">
<center><h2>Total Employee Hours In Last 1 Week </h2></center>
<center><h3 class="lead">( From <%=1.week.ago.strftime("%D") %> to <%= Time.now.strftime("%D")%> )</h3></center>
  <p><%= link_to "Print PDF", reports_employee_hour_weekly_path(@report, :format => 'pdf'), :class => 'btn btn-success' %></p>
      <table id="myTable" class="table table-striped table-hover" style="max-width: 600px">
        <thead>
        <tr bgcolor="#FFFFFF">
          <th><font size="3px">Employee</font></th>
          <th><font size="3px">Total Hour(s)</font></th>
        </tr>
        </thead>
        <tbody>
            <tr class="info">
              <td>John Bates</td>
              <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Bates").id, created_at: [1.week.ago..Time.now]).sum(:hour) %></td>
            </tr>
            <tr class="info">
              <td>Matt Fierro</td>
              <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Fierro").id, created_at: [1.week.ago..Time.now]).sum(:hour) %></td>
            </tr>
            <tr class="info">
              <td>Billy Koslosky</td>
              <td><%= Serviceline.where(:employee_id => Employee.find_by(last_name: "Koslosky").id, created_at: [1.week.ago..Time.now]).sum(:hour) %></td>
            </tr>
        </tbody>
      </table>
  <select id="thechoices" class="form-control" style="max-width: 800px">
    <option>Select Employee to View More Details</option>
    <option value="johntab">John Bates</option>
    <option value="matttab">Matt Fierro</option>
    <option value="billtab">Bill Koslosky</option>
  </select>
  <br>
  <!--John's Hours-->
 <div id="johntab">
    <div class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">John Bates</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @weeklyhours1.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>

  <!--Matt's Hours-->
<div id="matttab">
    <div id="matttab" class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">Matt Fierro</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @weeklyhours2.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>


  <!--Bill's Hours-->
  <div id="billtab">
    <div id="billtab" class="panel panel-info" style="max-width: 800px"><div class="panel-heading">
      <h3 class="panel-title" align="left">Bill Koslosky</h3>
    </div></div>
    <table id="myTable" class="table table-striped table-hover table-condensed" style="max-width: 800px">
      <thead>
      <tr bgcolor="#FFFFFF">
        <th>#</th>
        <th>Ticket</th>
        <th>Category</th>
        <th>Service</th>
        <th>Action</th>
        <th>Position</th>
        <th>Hour</th>
      </tr>
      </thead>

      <tbody>
      <% @weeklyhours3.each do |serviceline| %>
          <tr class="info">
            <td><%= link_to serviceline.id, serviceline_path(serviceline), :class => "btn btn-link btn-xs"  %></td>
            <td><%= if serviceline.ticket; serviceline.ticket.ticket_info end %></td>
            <td><%= if serviceline.category; serviceline.category.category_name end %></td>
            <td><%= if serviceline.service; serviceline.service.service_name end %></td>
            <td><%= if serviceline.serviceaction; serviceline.serviceaction.action end %></td>
            <td><%= if serviceline.serviceposition; serviceline.serviceposition.position end %></td>
            <td><%= serviceline.hour %></td>
            <td><%= link_to 'Edit', edit_serviceline_path(serviceline), :class => "btn btn-primary btn-xs" %></td>
          </tr>
      <% end %>
      </tbody>
    </table></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
        $('#johntab').hide();
        $('#matttab').hide();
        $('#billtab').hide();
        $("#thechoices").change(function(){
            $('#johntab').hide();
            $('#matttab').hide();
            $('#billtab').hide();
            $("#" + this.value).show();
        });

        $("#thechoices").change();
    });
</script>

app/views/reports/service_revenue_monthly.html.erb
<div class="jumbotron">
  <center><h2>Services Revenue in Last 1 Month </h2></center>
  <center><h3 class="lead">( From <%=1.month.ago.strftime("%D") %> to <%= Time.now.strftime("%D")%> )</h3></center>
  <p><%= link_to "Print PDF", reports_service_revenue_monthly_path(@report, :format => 'pdf'), :class => 'btn btn-success' %></p>
<table id="myTable" class="table table-striped table-hover" style="max-width: 600px">
    <thead>
    <tr bgcolor="#FFFFFF">
      <th><font size="3px">Service Type</font></th>
      <th><font size="3px">Total Services</font></th>
      <th><font size="3px">Revenue</font></th>
    </tr>
    </thead>
    <tbody>
    <tr class="info">
      <td>Brakes</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id, created_at: [1.month.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id, created_at: [1.month.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr class="info">
      <td>Suspension</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id, created_at: [1.month.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id, created_at: [1.month.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr class="info">
      <td>Outside Services</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id, created_at: [1.month.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id, created_at: [1.month.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr bgcolor="#FFF1E5">
      <td><strong><font size="3px">Monthly Total </font></strong></td>
      <td><strong><font size="3px"><%= Serviceline.where(created_at: [1.month.ago..Time.now]).count %></font></strong></td>
      <td><strong><font size="3px"><%= number_to_currency(Serviceline.where(created_at: [1.month.ago..Time.now]).sum(:subtotal)) %></font></strong></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/reports/service_revenue_weekly.html.erb
<div class="jumbotron">
  <center><h2>Services Revenue in Last 1 Week </h2></center>
  <center><h3 class="lead">( From <%=1.week.ago.strftime("%D") %> to <%= Time.now.strftime("%D")%> )</h3></center>
  <p><%= link_to "Print PDF", reports_service_revenue_weekly_path(@report, :format => 'pdf'), :class => 'btn btn-success' %></p>
  <table id="myTable" class="table table-striped table-hover" style="max-width: 600px">
    <thead>
    <tr bgcolor="#FFFFFF">
      <th><font size="3px">Service Type</font></th>
      <th><font size="3px">Total Services</font></th>
      <th><font size="3px">Revenue</font></th>
    </tr>
    </thead>
    <tbody>
    <tr class="info">
      <td>Brakes</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id, created_at: [1.week.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Brakes").id, created_at: [1.week.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr class="info">
      <td>Suspension</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id, created_at: [1.week.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Suspension").id, created_at: [1.week.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr class="info">
      <td>Outside Services</td>
      <td><%= Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id, created_at: [1.week.ago..Time.now]).count %></td>
      <td><%= number_to_currency(Serviceline.where(:category_id => Category.find_by(category_name: "Outside Services").id, created_at: [1.week.ago..Time.now]).sum(:subtotal)) %></td>
    </tr>
    <tr bgcolor="#FFF1E5">
      <td><strong><font size="3px">Weekly Total</font></strong></td>
      <td><strong><font size="3px"><%= Serviceline.where(created_at: [1.week.ago..Time.now]).count %></font></strong></td>
      <td><strong><font size="3px"><%= number_to_currency(Serviceline.where(created_at: [1.week.ago..Time.now]).sum(:subtotal)) %></font></strong></td>
    </tr>
    </tbody>
  </table>
</div>